#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit this file will also be sourced.

# general settings
# redshift -03500 &
redshift -l 59.3:18.1 -t 6500:4000 &
xset r rate 300 50 &
~/.fehbg &
compton &

# add xdg paths
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

# add path to zsh config
export ZDOTDIR=$HOME/.config/zsh

# default programs
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="google-chrome-stable"

# start statusbar application
export PATH=$PATH:$HOME/.local/bin/statusbar    # source scripts for dwmblocks
export PATH=$PATH:$HOME/.local/bin/dmenu    # source scripts for dwmblocks
dwmblocks &
