#!/bin/sh
#
# Run when executing `startx`

[[ -f $XDG_CONFIG_HOME/X11/xprofile ]] && . $XDG_CONFIG_HOME/X11/xprofile

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Start dwm
ssh-agent dwm
