#!/bin/sh

HISTSIZE=1000000
SAVEHIST=1000000

export MANPAGER='nvim +Man!'
export MANWIDTH=999

# Add path to zsh config
export ZDOTDIR="$HOME/.config/zsh"

# Software variables
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="google-chrome-stable"

# Add xdg paths
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Export to PATH
export PATH="$XDG_DATA_HOME/cargo/bin:$PATH"
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# Add paths for X
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
# export XSERVERRC="$XDG_CONFIG_HOME/X11/xserverrc"

# Set Go varaibles
export GOPATH="$HOME/.local/share/go"
export PATH="$PATH:$GOPATH/bin"
export GOBIN="$HOME/go/bin"
export PATH="$PATH:$GOBIN"
export GOPATH="$GOPATH:$HOME/go"
# export GOROOT="/usr/bin/go"
# export PATH="$PATH:$GOROTT/bin"

# Google Cloud
# export CLOUDSDK_CORE_PROJECT="master-thesis-342011"
export BOTO_PATH="$HOME/.config/gcloud/configurations/boto"

# Clean up home directory
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export HISTFILE="$XDG_STATE_HOME/zsh/history"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export GVIMINIT='let $MYGVIMRC = !has("nvim") ? "$XDG_CONFIG_HOME/vim/gvimrc" : "$XDG_CONFIG_HOME/nvim/init.lua" | so $MYGVIMRC'
export VIMINIT='let $MYVIMRC = !has("nvim") ? "$XDG_CONFIG_HOME/vim/vimrc" : "$XDG_CONFIG_HOME/nvim/init.lua" | so $MYVIMRC'
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export CONDARC="$XDG_CONFIG_HOME/conda/condarc"
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
export STARSHIP_CACHE="$HOME/.cache/starhip"
export IPYTHONDIR="$XDG_CONFIG_HOME/jupyter"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export KERAS_HOME="$XDG_DATA_HOME/keras"

# Export gpg tty
export GPG_TTY=$(tty)

# For QT Themes
export QT_QPA_PLATFORMTHEME=qt5ct

# Enable miniconda
[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh

# Better node manager
eval "$(fnm env)"

# Visited directory heuristic
eval "$(zoxide init zsh)"

# Set starship prompt
eval "$(starship init zsh)"
