#!/bin/sh

HISTSIZE=1000000
SAVEHIST=1000000

export MANPAGER='nvim +Man!'
export MANWIDTH=999

# add path to zsh config
export ZDOTDIR="$HOME/.config/zsh"

# default programs
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="google-chrome-stable"

# Export to PATH
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/share/go/bin:$PATH"
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# add xdg paths
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# add paths for X
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
# export XSERVERRC="$XDG_CONFIG_HOME/X11/xserverrc"

# clean up home directory
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export HISTFILE="$XDG_STATE_HOME/bash/history"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export GVIMINIT='let $MYGVIMRC = !has("nvim") ? "$XDG_CONFIG_HOME/vim/gvimrc" : "$XDG_CONFIG_HOME/nvim/init.lua" | so $MYGVIMRC'
export VIMINIT='let $MYVIMRC = !has("nvim") ? "$XDG_CONFIG_HOME/vim/vimrc" : "$XDG_CONFIG_HOME/nvim/init.lua" | so $MYVIMRC'

# Export go path
export GOPATH="$HOME/.local/share/go"

# Default options for `fzf`
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export FZF_DEFAULT_COMMAND="find ."

# eval "$(fnm env)"
# eval "$(zoxide init zsh)"

# set starship prompt
eval "$(starship init zsh)"
