#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.fnm:$PATH
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
# eval "$(fnm env)"
# eval "$(zoxide init zsh)"

# set starship prompt
eval "$(starship init zsh)"
